### ISSUE TITLE
000011 - 删除指定目录下的文件（*.txt）

### ISSUE THREAD

**Issue by FirminSun** [FirminSun/zjai-fusion#11]
Hi  秋泉；
实现一个脚本功能：根据文件后缀（*.txt） ，删除文件。
**Note That：**
测试过程，删除操作需要小心，可以用 rename 做尝试， 比如：*.txt  ==> *.aa 视作删除操作。

**Comment by Zhanqiuquan** [comment]
Hi，孙工
完成指定目录下文件（*.txt）的删除；
步骤如下：
首先，在指定目录下创建before文件夹，将所有文件copy至../before/目录下
再次，在指定目录下创建delect文件夹，将所有后缀（.txt）文件move至../delect/目录下
最后，在指定目录下创建after文件夹，将所有非后缀（.txt）文件move至../after/目录下
@jaykky01

**Comment by jaykky01** [comment]
Hi，秋泉：
思路很清晰；
在此提出一些可以提高代码扩展性、以及可读性的建议：
1.makedir函数，在文件已存在的时候将可能报错，建议加个判断检测文件是否存在，则无需重复修改代码；
2.可将后缀名类别 作为 一个参数抽出来，目前场景是txt，后续若是jpg等等的场景，只需要修改传入参数值即可；
3.可创建log.txt用于记录什么文件被移到delete文件夹； @Zhanqiuquan

**Comment by FirminSun** [comment]
Nice job.
