### ISSUE TITLE
00012 - 增加obj、bg类，在融合前增加数据预处理环节

### ISSUE THREAD

**Issue by jaykky01** [FirminSun/zjai-fusion#12]
Hi，孙工：
将融合物体（objs）、背景（bg）进行元素化，构建新的类别。主要作用在于，在主体流程（数据预处理-->检测可填充位置 --> 进行背景融合 -->保存） 不变的情况下，在数据预处理过程中改变融合物体、背景的样式，进行融合，即可开展更多的融合方案。

**Comment by FirminSun** [comment]
Hi 炬康；
关于融合数据的中间输出，存放到output 目录下.

**Comment by jaykky01** [comment]
Hi，all：
目前共增加bg_factory/obj_factory/generator/fusion_factory四大类，其中：
1.bg_factory是表示背景对象，包括了背景的操作方法；
2.obj-factory是表示物体对象，包括了物体的操作方法、数据增强方法、融合时的新size等
3.generator（孙工代码基础上新增接口方法）主要完成数据批量抽取功能，将数据列表转成轮转型输入数据，将读取到的bg、obj分别接入bg_factory/obj_factory进行处理后，返回；
4.fusion_factory主要完成数据融合功能；接入generator输出的数据，进行流程式的运行，可通过参数设置调整是否运行，最终保存融合结果；

**Comment by FirminSun** [comment]
You did a great job.
