### ISSUE TITLE
00016 - 检查抠图结果标签

### ISSUE THREAD

**Issue by FMsunyh** [FirminSun/zjai-fusion#16]
Hi,秋泉：
为了保证上传的抠图数据的准确性，现需要你编写一个脚本，作为数据汇总后，检查标签是否正确，无误才能上传；
目前初定功能为：
扫描数据包中所包含的所有商品类别标签，并与标准的300类classes.txt作对比，检测是否存在标签不在300类商品中。

完成脚本后，教一下慧聪怎么使用。

@jaykky01

**Comment by Zhanqiuquan** [comment]
Hi，all；
解决思路：
step-1：读取父路径的labels数据，生成list_stad数据
step-2：读取txt文件的labels数据，生成list_check数据
step-3：对比list_stad与list_check，并输出不同的lis元素
以上。

**Comment by Zhanqiuquan** [comment]
Hi，all；
已教慧聪使用。
以上。

**Comment by FirminSun** [comment]
Hi 秋泉；
Nice job.
