### ISSUE TITLE
00017 - 编写脚本实现自动化创建文件目录，修改拍摄数据随机重命名代码

### ISSUE THREAD

**Issue by jaykky01** [FirminSun/zjai-fusion#17]
Hi，秋泉：
现需要你编写一个脚本，主要功能为，根据商品信息列表（excel），自动化创建文件目录，每个类别创建一个以 序号_商品名称_口味_英文标签  命名的文件，方便拍照数据存放和查找；

同时需要你修改原有 针对拍摄数据进行随机重命名  的代码，对接上述功能，主要在于，原有功能直接读取文件名称作为商品标签，需要修改为  截取英文标签部分做为 商品标签。 @Zhanqiuquan

**Comment by FirminSun** [comment]
Hi 秋泉；
更新该问题的状态?

**Comment by FirminSun** [comment]
Hi 秋泉；
Nice job.
I am going to close this issue.
please let me know if you have more question about this issue.
