### ISSUE TITLE
00018 - 编写脚本对商品汇总excel表进行按包装类型分类商品

### ISSUE THREAD

**Issue by jaykky01** [FirminSun/zjai-fusion#18]
Hi，all：
增加一个功能，实现：
1.按照商品包装类型对商品进行分类；
2.使用简单的唯一标示作为ID，进行标记商品，如ID为gz_001 ,即罐装包装的第一个商品，可见excel结果表

**Comment by FirminSun** [comment]
Hi  秋泉；
学习一下，这个脚本。

**Comment by Zhanqiuquan** [comment]
Hi，all；
脚本已认真学习一遍，有很多地方值得学习。
确定往后脚本编写的方向：
1-函数定义的更加明确、简洁。一个函数仅仅实现一个功能。
2-脚本的思路清晰。不宜将过多步骤、功能堆砌一块，降低脚本的可读性。
3-美观。注意整体脚本的规范、协调。代码的长度、间隔规范。
以上。
谢谢炬康，孙工。 @jaykky01 @FirminSun
