### ISSUE TITLE
00020 - 以voc数据集作为背景的融合功能

### ISSUE THREAD

**Issue by jaykky01** [FirminSun/zjai-fusion#20]
Hi，孙工：
已实现以voc数据集作为背景的融合功能；主要思路
- 第一步：检测背景类型（bg or voc？），读取背景中物体属性，若为背景则为空；
- 第二步：将voc类型背景看做已迭代融合的图像；
- 第三步：在背景基础上继续融合且保存即可
@FMsunyh

**Comment by FirminSun** [comment]
Hi 炬康；
you are so smart.
Then, you can continue to do fusion and training.

**Comment by FirminSun** [comment]
Hi 炬康；
I will close this issue.
please let me know if you have any  other idea about this issue.
