### ISSUE TITLE
00021 - 500类数据，现场采集第二轮

### ISSUE THREAD

**Issue by FirminSun** [FirminSun/zjai-fusion#21]
Hi 秋泉，
500类数据，现场采集第二轮
* 每张图片3-5个商品
* 每10个商品采集50张

**Comment by jaykky01** [comment]
Hi，秋泉：
此轮数据采集工作的注意事项：
- 拍摄数据先预处理，然后机器预标，再到人为标注
- 增加结算台摄像头视角；
- 类别很多，标注时注意口味的细节变化

此轮数据采集任务，与商品入库的第一阶段商品标签粘贴工作同步；
@Zhanqiuquan

**Comment by Zhanqiuquan** [comment]
Hi，all；
第二轮采集计划，明天（2018/11/06）确定所有流程，明天下午6点更新该状态。
以上。

**Comment by Zhanqiuquan** [comment]
Hi，all；
采集-标注工作流程（20类商品为一组，完成一组工作需要2小时，迭代完成所有商品）
1--检索商品（负责：兼职，协助：慧聪）
---- 找到商品、找到对应标签、贴标签（入库管理）
---- 检索商品一组需要20分钟
2--拍照采集（负责：兼职）
---- 采集一组需要40分钟
3--机器预标注（负责：秋泉，协助：炬康）
---- 时间不计
4--人工完善标注（负责：兼职）
---- 标注一组需要1小时
以上。 @jaykky01 @FirminSun

**Comment by jaykky01** [comment]
Hi，秋泉：
定位影响工作时长的关键因素；
思考如何提高 步骤一、步骤二、步骤四工作效率；
@Zhanqiuquan

**Comment by jaykky01** [comment]
Hi,all：
截止今天（11-08）完成136类（137/416）商品采集并标注；

**Comment by jaykky01** [comment]
截止今天（11-12）完成254类（254/416）商品采集并标注；

**Comment by Zhanqiuquan** [comment]
Hi all；
截止昨天（11-13）完成314类（314/416）商品采集并标注；同时完成仓库所有商品的编号制作，并入库。

**Comment by jaykky01** [comment]
Hi，孙工、秋泉：
我已合并此前采集的UA+现场数据、抠图数据，并放置到相应的地方；
在此对合并数据提出以下建议：
-数据包命名应有日期及类别数目，若更新，则修改为更新日期；
-数据放置在对应文件路径下，且在readme.txt提供数据说明；
秋泉，可参考以上方法；

**Comment by Zhanqiuquan** [comment]
Hi all；
截止昨天（11-14）完成344类（314/416）商品采集并标注；

**Comment by FirminSun** [comment]
Hi all;
合并后的数据存放在哪里？
数据有变动，邮件通知一下.

**Comment by jaykky01** [comment]
Hi，all:
此阶段汇总数据(不包含下架商品)已上传至179-ftp，共390类，2207张；
路径为：/shop_train_data_500s/train_data_2018-11-15_390classes_second.zip

**Comment by FirminSun** [comment]
Hi all;
I am going to close issue if done?
