### ISSUE TITLE
00022 - 修改Annotation中的label标签信息

### ISSUE THREAD

**Issue by jaykky01** [FirminSun/zjai-fusion#22]
Hi，秋泉：
增加一个功能，修改VOC数据集中所有含有xxx_label的xml标签数据改成 xxx_xxx_label，并重新保存下来；
建议：可直接使用xml_manger.py 以及 记录log
@Zhanqiuquan

**Comment by FirminSun** [comment]
Hi  秋泉；
How about the issue going?
Please update the status and let us know if you have any issue.

**Comment by Zhanqiuquan** [comment]
Hi，all；
This issue has been completed. Related code has been uploaded.
end.
@jaykky01 @FirminSun

**Comment by FirminSun** [comment]
Good job.
