### ISSUE TITLE
00023 - 455类商品模型测试工作

### ISSUE THREAD

**Issue by jaykky01** [FirminSun/zjai-fusion#23]
Hi，秋泉：
按以下方案开展455类商品融合工作（优先级从高到低，先完成ab）：
a.以单个商品现场数据（voc数据集）作为背景，融合5000张数据；
b.以UA+现场数据作为背景，融合5000张数据；
c.以5000张外景大背景（宽高大于2000）作为背景输入，输出等比例resize至宽高1000左右，融合40000张数据；
d.以5000张外景小背景（宽高600～1000）作为背景输入，输出不做resize，融合40000张数据；
@Zhanqiuquan

**Comment by jaykky01** [comment]
Hi，秋泉：
按以下方案开展455类商品模型测试工作（优先级从高到低，先完成ab）：
A.测试融合任务a数据，并反馈测试结果；
B.测试融合任务b数据，并反馈测试结果；
C.随机选出2000张136类商品真实外景数据，进行测试并反馈结果；
D.测试融合任务c数据，并反馈测试结果；
E.测试融合任务d数据，并反馈测试结果；
@Zhanqiuquan

**Comment by Zhanqiuquan** [comment]
Hi all;
截止昨天（11-13），融合及训练进度情况如下：
融合：
---- 已完成方案a，b 和 d 的融合
---- 未完成方案c  计划于明天早上（11-15）完成
测试：
---- 已完成方案A 和 B 的测试，测试结果将于所有测试完成，统一汇报
---- 未完成方案C 计划今天完成测试
---- 未完成方案D 和 E 计划明天开始测试
以上。 @jaykky01 @FirminSun

**Comment by Zhanqiuquan** [comment]
Hi all;
截止昨天（11-14），融合及训练进度情况如下：
融合：
---- 已完成所有方案的融合
测试：
---- 已完成方案A 和 B 的测试，测试结果将于所有测试完成，统一汇报
---- 未完成方案C 计划今天早上开始测试
---- 未完成方案D 和 E 计划今天下午开始测试
以上。 @jaykky01 @FirminSun

**Comment by Zhanqiuquan** [comment]
Hi all;
截止昨天（11-15），融合及测试情况如下，
1. 融合：
- 已完成所有方案的融合
2. 测试：
- 已完成方案A 、B 和 E  的测试
- 未完成方案C 计划下周开始测试，目前正在进行外景数据标注工作
- 未完成方案D 计划今天开始测试
以上。 @jaykky01 @FirminSun

**Comment by Zhanqiuquan** [comment]
Hi all；
融合模型测试结果如下，
1. 455类商品UA+场景测试集（共5000张，451类）
- 数据较为均衡，每类商品出现次数主要集中在20-150内，离散类别不多；
- 精确率：99%，召回率：99% 
2. 455类商品VOC场景测试集（共5000张，451类）
数据较为均衡，每类
- 商品出现次数主要集中在20-100内，离散类别不多；
- 精确率：99%，召回率：99% 
3. 455类商品外景小背景测试集（共40000张，451类）
- 数据较为均衡，每类商品出现次数主要集中在400-800内，离散类别不多；
- 精确率：98.8%，召回率：98.9% 
以上。 @jaykky01 @FirminSun

**Comment by Zhanqiuquan** [comment]
Hi all；
融合模型测试结果如下（补充），
1. 方案D-455类商品外景大背景测试集（共40000张，451类）
- 数据较为均衡，每类商品出现次数主要集中在400-800内，离散类别不多；
- 精确率：99.2%，召回率：99.5%
以上。 @jaykky01 @FirminSun

**Comment by FirminSun** [comment]
Hi  秋泉;
Nice working.
keep learning.
