### ISSUE TITLE
00005 - 数据增强功能

### ISSUE THREAD

**Issue by FirminSun** [FirminSun/zjai-fusion#5]
Hi 炬康；
添加数据功能: 
- 旋转：至于角度，思考一下.
- 缩放

**Comment by jaykky01** [comment]
Hi，孙工：
已完成随机旋转、缩放 两个方式的数据增强功能；主要思路如下：
1.从抽取数据得到原始图像obj进行数据增强处理（数据增强方式）；
2.对处理完成后的图像创建mask（create_mask函数）；
3.通过mask找到实际大小的box（find_boxes函数）；
4.从原始图像中裁剪出实际大小的图像，并输出作为融合所用的obj

**Comment by FirminSun** [comment]
Hi 炬康；
Nice work.
