### ISSUE TITLE
00006 - 指定obj_png数据包

### ISSUE THREAD

**Issue by FirminSun** [FirminSun/zjai-fusion#6]
Hi 炬康；
添加一个功能，可指定obg_png 数据包， 可指定多个。

**Comment by jaykky01** [comment]
Hi，孙工：
   此功能已经添加了。主要思路如此前一致，把路径设成list，遍历读取加载。

**Comment by FirminSun** [comment]
Hi  炬康；
Nice job；
很好的学习路子.
