### ISSUE TITLE
00007 - 指定融合的label

### ISSUE THREAD

**Issue by FirminSun** [FirminSun/zjai-fusion#7]
Hi 炬康；
添加一个功能，可以指定融合的label。
即：过滤掉不需要融合的label。

**Comment by jaykky01** [comment]
Hi，孙工：
目前已完成此功能，增；主要思路如下：
1.通过设置target_classes_path，读取需要融合的label的txt文件；
2.在读取obj时，进行过滤即可；
当然若是不需要过滤的时候，只需要输入一个包括全部label的txt或json文件即可

**Comment by FirminSun** [comment]
Very nice implementation
