### ISSUE TITLE
00008 - 抠图任务

### ISSUE THREAD

**Issue by FirminSun** [FirminSun/zjai-fusion#8]
Hi all;
关于抠图的issue 放到这里讨论.

关于抠图的文件包命名：
昨日上传的文件为：mask_2018-09-26.zip 
 
今后统一修改为：
obj_png_2018-09-26.zip  （日期为当日）

**Comment by FirminSun** [comment]
Hi 秋泉；
针对obj_png文件名问题，写一个脚步(obj_png_rename.py)，修正一下：
统一为：**label-name_date_id**。
比如：**aebs-aebsytbbt-dz-hhkw-120g_2018-09-27_1**

时间：当日日期
id：自增

@Zhanqiuquan @jaykky01

**Comment by FirminSun** [comment]
Hi  炬康；
接手这个rename 工作，然后交付给秋泉使用.

**Comment by jaykky01** [comment]
Hi，孙工：
 已完成此功能代码编写，并已交付使用。
 将上传至data_processing文件中。

**Comment by Zhanqiuquan** [comment]
抠图今日汇总情况：
共完成抠图类别：91类，每类label图片约15-20张。
已压缩打包为obj_png_2018-09-29.zip，并上传至ftp: /syh_fusion_data。

**Comment by Zhanqiuquan** [comment]
Hi all；
抠图今日汇总情况：
共完成抠图类别：91类，每类label图片约15-20张。
已压缩打包为obj_png_2018-09-29.zip，并上传至ftp: /syh_fusion_data。

**Comment by FirminSun** [comment]
Hi all;
关于数据存放问题：
- 暂时都放在179-FTP. 
  - 抠图的原数据： /data/syh_fusion_data/matting_origin_data 
  - 数据包名称：matting_origin_data_2018-10-08_23classes.zip  （23classes为类别总数）
  - 摄影棚采集的数据，存放于此
 
- 扣好之后的数据：/data/syh_fusion_data/matting_obj_png_data 
  - 数据包名称：obj_png_2018-10-08_23classes.zip  （23classes为类别总数）
  - 扣好的图，存放在此

**Comment by Zhanqiuquan** [comment]
Hi，all；
目前完成抠图99类label，
压缩为obj_png_2018-10-09.zip，
上传至/data/syh_fusion_data/matting_obj_png_data/obj_png_2018-10-09.zip
每一类label包含15-20张样品图像。
包含缺少的label 7类，以及召回率低的2类（其中召回率低的2类已下架，没有抠这部分的图）
以上。

**Comment by Zhanqiuquan** [comment]
Hi，all；
目前完成抠图132类label(包含之前的99类)，
压缩为obj_png_2018-10-11_132classes.zip，
上传至/data/syh_fusion_data/matting_obj_png_data/obj_png_2018-10-11_132classes.zip
每一类label包含20张样品图像

**Comment by FirminSun** [comment]
Hi all；
第一轮抠图任务已经完成.
